/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AAlert: typeof import('ant-design-vue/es')['Alert']
    AButton: typeof import('ant-design-vue/es')['Button']
    ACheckbox: typeof import('ant-design-vue/es')['Checkbox']
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
    ADropdown: typeof import('ant-design-vue/es')['Dropdown']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AInput: typeof import('ant-design-vue/es')['Input']
    AInputPassword: typeof import('ant-design-vue/es')['InputPassword']
    AlipayOutlined: typeof import('@ant-design/icons-vue')['AlipayOutlined']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    AnnouncementRibbon: typeof import('./../src/components/Notify/AnnouncementRibbon.vue')['default']
    ASpace: typeof import('ant-design-vue/es')['Space']
    ATabPane: typeof import('ant-design-vue/es')['TabPane']
    ATabs: typeof import('ant-design-vue/es')['Tabs']
    ConcatCaptcha: typeof import('./../src/components/Captcha/ConcatCaptcha.vue')['default']
    ConfirmTextButton: typeof import('./../src/components/Button/ConfirmTextButton.vue')['default']
    CropperModal: typeof import('./../src/components/CropperModal/index.vue')['default']
    DeleteTextButton: typeof import('./../src/components/Button/DeleteTextButton.vue')['default']
    DictBadge: typeof import('./../src/components/Dict/display/DictBadge.vue')['default']
    DictCheckboxGroup: typeof import('./../src/components/Dict/group/DictCheckboxGroup.vue')['default']
    DictRadioGroup: typeof import('./../src/components/Dict/group/DictRadioGroup.vue')['default']
    DictSelect: typeof import('./../src/components/Dict/group/DictSelect.vue')['default']
    DictTag: typeof import('./../src/components/Dict/display/DictTag.vue')['default']
    DictTagGroup: typeof import('./../src/components/Dict/display/DictTagGroup.vue')['default']
    DictText: typeof import('./../src/components/Dict/display/DictText.vue')['default']
    Editor: typeof import('./../src/components/Editor/index.vue')['default']
    IconSelector: typeof import('./../src/components/IconSelector/IconSelector.vue')['default']
    IconSelectorModal: typeof import('./../src/components/IconSelector/IconSelectorModal.vue')['default']
    LockOutlined: typeof import('@ant-design/icons-vue')['LockOutlined']
    Lov: typeof import('./../src/components/Lov/Lov.vue')['default']
    LovModal: typeof import('./../src/components/Lov/LovModal.vue')['default']
    LovSearch: typeof import('./../src/components/Lov/LovSearch.vue')['default']
    MailOutlined: typeof import('@ant-design/icons-vue')['MailOutlined']
    MobileOutlined: typeof import('@ant-design/icons-vue')['MobileOutlined']
    OperationGroup: typeof import('./../src/components/Operation/OperationGroup.vue')['default']
    RotateCaptcha: typeof import('./../src/components/Captcha/RotateCaptcha.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchActions: typeof import('./../src/components/Search/SearchActions.vue')['default']
    SelectLanguage: typeof import('./../src/components/SelectLanguage/index.vue')['default']
    SliderCaptcha: typeof import('./../src/components/Captcha/SliderCaptcha.vue')['default']
    TaobaoOutlined: typeof import('@ant-design/icons-vue')['TaobaoOutlined']
    UserOutlined: typeof import('@ant-design/icons-vue')['UserOutlined']
    WeiboOutlined: typeof import('@ant-design/icons-vue')['WeiboOutlined']
    WordClickCaptcha: typeof import('./../src/components/Captcha/WordClickCaptcha.vue')['default']
  }
}
